### PR TITLE
flist: Fix bounds-check, put items into heap

### LINKED ISSUE #1365: Run from source? / TailsOS
Okay so I was wondering if you could run uTox from source? after building I noticed the excutable, and it opens but I get errors which I will get to in a moment.

Also the same errors I get when opening the installed dpkg/.deb on Tails.

1. uTox version: Latest git
2. Operating system: Tails
3. Desktop Environment/Window Manager (Linux/BSD only):  Gnome

```
Settings:     Unable to parse utox_save.ini.
Settings:     Unable to open utox_save.
Settings:     Unable to load uTox settings. Use defaults.
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
flsit:        Index out bounds. Too many items have been created.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

Once I run it once, and its created some files it no longer gives errors about the settings, but the rest of the errors, but it also does not want to connect?

I remember somehow running it in portable mode, but I have tried `-p` and get the same results, and if running from source would it save / check the config files in the source directory or still check the .config/tox directory?

**Edit:** 

I see that running ./utox -p now creates the tox folder with the configs in but it still doesnt want to connect? and I get that old bug where changing any settings in the program crashes it, but I have to instead edit the config file. Here is the errors I get;

```
XLib Tray:    Incoming tray window event (28)
XLib tray:    Reached end of function, this is bad juju!
flsit:        Index out bounds. Too many items have been created.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

### PR DESCRIPTION
**Pull request by avoidr**
Closes #1365

---
This change is [Reviewable](https://reviewable.io/reviews/utox/utox/1369)

### CODE REVIEW

**Comment by GrayHatter** [comment]
I approve of this PR, but it's gonna take me some time to review... keep poking me on IRC and I'll get it done

**Comment by avoidr** [comment]
Thanks!

File: src/flist.c [hunk 1]
```diff
@@ -274,19 +274,23 @@ void flist_update_shown_list(void) {
...
 
+/* returns address of item at current index and appends the group create entry */
 static ITEM *newitem(void) {
-    unsigned int index = itemcount - 1;
-    if (index >= MAX_ITEMS) {
-        LOG_ERR("flsit", "Index out bounds. Too many items have been created.");
+    item       = realloc(item, (itemcount + 1) * sizeof(ITEM));
+    shown_list = realloc(shown_list, (itemcount + 1) * sizeof(uint32_t));
+    if (!item || !shown_list) {
+        LOG_ERR("flist", "Not enough memory to allocate for another item, currently.");
```
Comment (GrayHatter) [inline src/flist.c]: this needs to be fatal, or you need to free the previous pointer which is now out of scope...

It should be fatal...

File: src/flist.c [hunk 2]
```diff
@@ -605,17 +609,25 @@ void flist_start(void) {
...
 
-    item_add.item      = ITEM_ADD;
-    item_settings.item = ITEM_SETTINGS;
+    item_add.type      = ITEM_ADD;
+    item_settings.type = ITEM_SETTINGS;
 
+    itemcount = self.friend_list_count + self.groups_list_count;
+    itemcount += 1; /* for ITEM_GROUP_CREATE */
+
+    item       = malloc(itemcount * sizeof(ITEM));
```
Comment (GrayHatter) [inline src/flist.c]: calloc here

File: src/flist.c (hunk 1 above)
Comment (avoidr) [reply src/flist.c]: I don't see it going out of scope, since it's a realloc to a global pointer. That global pointer simply received a new address.
I've thought of the case `item && !shown_list` and didn't see an issue.
